### ISSUE TITLE
image linking toolkit

### ISSUE THREAD

**Issue by samalloing** [libis/crkc_tools#11]
Op basis van de webservices zou er een toolkit gemaakt moeten worden waardoor het gemakkelijk is om image links (Digitool / Rosetta) toe te voegen, te verwijderen en te updaten.

De input is een bestand met het label, idno en pid. De bestanden worden opgezocht op basis van de idno en de pid wordt gelinkt,gedelete of geupdate.

@roxannewyns

**Comment by aruijmen** [comment]
Controle:
In de databank zitten nog 183 volledige digitoolUrls. (element_id:202)
Als we de status deleted=0 bijvoegen, blijven er nog 44 records over.
Deze behoren allemaal toe aan POV.
Maar, blijkbaar zijn deze records NIET geïndexeerd in Solr, want met de REST API  (mijn programma) krijg ik GEEN resultaten.
Heb ter controle één records geëditeerd (object_id = 136282) in de client, door het toe te voegen aan de geëigende collectie: record wordt geïndexeerd in Solr, en mijn programma kan lopen.
Ik heb steekproef gewijs nog andere object_ids gecontroleerd, en deze bleken ook allemaal GEEN collectie te hebben.
(Misschien is dat één van de redenen waarom bepaalde records NIET door Solr worden geïndexeerd, nl omdat 'verplichte' velden ontbreken.  Het record wordt wel aangemaakt in sql, maar niet geïndexeerd in Solr. ??????)

Het gaat om volgende objecten:
135859
136349
136352
136380
136387
136394
136412
136444
136628
137264
137270
137276
137355
139039
139071
139092
139151
139195
139214
146875
147745
153442
153457
161305

Deze melding kan dus gesloten worden. 
(Zal dat dus dadelijk doen met mijn programma)

Ter info: de sql-query:

SELECT obj.object_id, obj.idno from ca_objects obj
inner join ca_attributes as att on obj.object_id = att.row_id 
inner join ca_attribute_values as val on att.attribute_id = val.attribute_id 
where att.table_num = 57 and val.element_id = 202 and val.value_longtext1 like '%VIEW%' 
and obj.deleted = 0

**Comment by samalloing** [comment]
Hoe is deze commit een fix voor het issue?

**Comment by aruijmen** [comment]
Oeps. per ongeluk het verkeerde issue genomen (moest 12 zijn ipv 11)

**Comment by roxannewyns** [comment]
@samalloing 
Is dit nog van toepassing nu Rosetta er is? Moet er niet gewerkt worden aan een Rosetta toolkit?

**Comment by samalloing** [comment]
Dit is nog altijd relevant; De naam moet idd aangepast worden, maar het gaat hier over een toolkit om aanpassingen te doen in CollectiveAccess en niet over Rosetta.

**Comment by naeemmuhammad** [comment]
Image linking tool: https://github.com/libis/collectiveaccess_tools/commit/974e6a7c96fe41cd898b136834fbc0869529ced8
