### ISSUE TITLE
alle POV objecten verwijderen

### ISSUE THREAD

**Issue by roxannewyns** [libis/crkc_tools#22]
assigned @aruijmen 

Alle POV objecten mogen verwijderd worden.

Kan je via de API alle object records deleten uit de interface?

**Comment by roxannewyns** [comment]
Soft deletion van alle POV en PWV records via API. Records staan nog in ca_crkc database. Ook afbeeldingen voorlopig nog in Digitool. Binnen jaar of eerder mag alles permanent uit de database en Digitool verwijderd worden.

**Comment by roxannewyns** [comment]
assigned @aruijmen 
Alle POv records mogen verwijderd worden uit de databank.

**Comment by aruijmen** [comment]
Done!!!!!
