### ISSUE TITLE
dubbele nummers (KV nummers) wijzigen

### ISSUE THREAD

**Issue by roxannewyns** [libis/crkc_tools#23]
assigned @aruijmen 

Er waren een aantal dubbele inventarisnummers bij het opkuisen van de KV nummers. 
Op de L schijf onder Heron\CRKC\Anita kan je de lijst met het oude nummer en het nieuwe nummer terugvinden. Kan je dit aanpassen via API a.u.b.?

**Comment by aruijmen** [comment]
Bij het verwijderen van de KV_-nummers zijn volgende problemen overgebleven:


PA.171.FB - (KV_50359)	PA.171.F040
PA.171.FB - (KV_50189)	PA.171.F039	
PA.005.I002 - (KV_42340)	PA.005.I010	
PA.171.FB	PA.171.F038	
PA.171.FC	PA.171.F041	

Deze wijzigingen zijn mislukt, omdat de nieuwe idno al bestaat. (duplicates niet mogelijk)

CRKC.0159.0253 - (KV_104737)	CRKC.0159.0603	KV_104737	

Dit record staat op deleted
